config/routes.rb
Rails.application.routes.draw do
  get 'usertasklists/create'
  get 'usertasklists/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "tasks#index"
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  patch 'tasks/:id', to: 'tasks#update'
  
  resources :tasks, only: [:index, :show, :new, :create,:edit,:destroy]
  resources :users, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    
    validates :content, presence: true, length: { maximum: 255 }
    validates :status, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :tasks
end

app/models/usertasklist.rb
class Usertasklist < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
  validates :title, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :require_user_logged_in
    before_action :correct_user, only: [:edit, :update,:destroy,:show]
    
    def index
      if logged_in?
        @task = current_user.tasks.build  # form_with 用
        @tasks = current_user.tasks.order(id: :desc).page(params[:page])
      end
    end
    
    def create
        # @task = Task.new(task_params) 
        @task = current_user.tasks.build(task_params)

        if @task.save
          flash[:success] = 'Task が正常に投稿されました'
          redirect_to @task
        else
          flash.now[:danger] = 'Task が投稿されませんでした'
          render :new
        end
        
    end 
    
    def new 
        @task = Task.new
    end 
    
    def edit 
        @task = Task.find(params[:id])
    end 
    
    def show 
        @task= Task.find(params[:id])
    end 
    
    def update
        @task = Task.find(params[:id])

        if @task.update(task_params)
          flash[:success] = 'Task は正常に更新されました'
          redirect_to @task
        else
          flash.now[:danger] = 'Task は更新されませんでした'
          render :edit
        end
    end
    
    def destroy
        @task = Task.find(params[:id])
        @task.destroy
    
        flash[:success] = 'Task は正常に削除されました'
        redirect_to tasks_url
    end
    
    private

  # Strong Parameter
    def task_params
       params.require(:task).permit(:content, :status, :task)
    end
    
    def correct_user
      @task = current_user.tasks.find_by(id: params[:id])
      unless @task
        redirect_to root_url
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/usertasklists_controller.rb
class UsertasklistsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]

  def create
    if logged_in?
      @usertasklist = current_user.usertasklists.build(usertasklist_params)
      if @usertasklist.save!
        flash[:success] = 'メッセージを投稿しました。'
        redirect_to root_url
      else
        @usertasklists = current_user.usertasklists.order(id: :desc).page(params[:page])
        flash.now[:danger] = 'メッセージの投稿に失敗しました。'
        render 'tasks/index'
      end
    end
  end

  def destroy
    if logged_in
      @usertasklist.destroy
      flash[:success] = 'メッセージを削除しました。'
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def usertasklist_params
    params.require(:usertasklist).permit(:content,:title)
  end
  
  def correct_user
    @usertasklist = current_user.usertasklists.find_by(id: params[:id])
    unless @usertasklist
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usertasklists_helper.rb
module UsertasklistsHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_type, task| %>
  <div><%= task %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/flash_tasks' %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @task, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :content, 'タスク内容' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :status, 'タスクステータス' %>
        <%= f.text_field :status, class: 'form-control' %>
      </div>
      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
<% end %>

app/views/tasks/edit.html.erb
<p1>編集ページ</p1>

<%= render 'form', task: @task %>

<%= link_to '戻る', tasks_path %>

app/views/tasks/index.html.erb
<% if logged_in? %>
  <h1>タスク一覧</h1>
  
  <ul>
    <% @tasks.each do |task| %>
      <li><%= link_to task.id, task %>:<%= task.status %>:<%= task.content %></li>
    <% end %>
  </ul>
  
  <%= link_to '新規タスクの投稿', new_task_path %>
  <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
<% end %>

app/views/tasks/new.html.erb
<h1>作成ページ</h1>

<%= render 'form', task: @task %>

<%= link_to "戻る", tasks_path %>

app/views/tasks/show.html.erb
<h1>詳細ページ</h1>

<p><%= @task.status %></p>
<p><%= @task.content %></p>

<p><%= link_to "戻る", tasks_path%></p>
<%= link_to 'このタスクを編集する', edit_task_path(@task) %>
<%= link_to 'このタスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p><%= link_to 'Go to Task', tasks_path%></p>

app/views/usertasklists/_usertasklists.html.erb
<ul class="list-unstyled">
  <% usertasklists.each do |usertasklist| %>
    <li class="media mb-3">
      <div class="media-body">
        <div>
          <%= link_to usertasklist.user.name, user_path(usertasklist.user) %> <span class="text-muted">posted at <%= usertasklist.created_at %></span>
        </div>
        <div>
          <p>title : <%= usertasklist.title %></p>
          <p>task : <%= usertasklist.content %></p>
        </div>
        <div>
          <% if current_user == usertasklist.user %>
            <%= link_to "Delete", usertasklist, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate usertasklists %>
  <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
</ul>